import type { ColumnDef } from '../types'

export const COLUMNS: ColumnDef[] = [
  { key: 'date', label: '发表年月', defaultVisible: true, sortable: true },
  { key: 'year', label: '年份', defaultVisible: false, sortable: true },
  { key: 'title', label: '题目', defaultVisible: true, sortable: true },
  { key: 'journal', label: '刊物', defaultVisible: true, sortable: true },
  { key: 'volume', label: '卷', defaultVisible: true, sortable: true },
  { key: 'issue', label: '期', defaultVisible: true, sortable: true },
  { key: 'pages', label: '页码', defaultVisible: true },
  { key: 'impactFactor', label: '当年IF', defaultVisible: true, sortable: true },
  { key: 'cas', label: '中科院分区', defaultVisible: true, sortable: true },
  { key: 'indexing', label: '收录', defaultVisible: true },
  { key: 'firstAuthor', label: '第一作者', defaultVisible: true, sortable: true },
  { key: 'authors', label: '全部作者', defaultVisible: false },
  { key: 'correspondingAuthor', label: '通讯作者', defaultVisible: true },
  { key: 'coFirst', label: '共一', defaultVisible: true },
  { key: 'rank', label: '排名', defaultVisible: true, sortable: true },
  { key: 'totalAuthors', label: '总人数', defaultVisible: true, sortable: true },
  { key: 'myContribution', label: '本人贡献', defaultVisible: false },
  { key: 'citations', label: '引用', defaultVisible: false, sortable: true },
  { key: 'pubmed', label: '链接', defaultVisible: true },
  { key: 'pdfFull', label: '全文PDF', defaultVisible: true },
  { key: 'pdfFirst', label: '首页PDF', defaultVisible: true },
  { key: 'ris', label: 'RIS', defaultVisible: false },
  { key: 'id', label: 'ID', defaultVisible: false },
]
